# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 200, 350, 351))
        self.groupBox.setMaximumSize(QtCore.QSize(700, 600))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.listaEncendidos = QtWidgets.QListWidget(self.groupBox)
        self.listaEncendidos.setGeometry(QtCore.QRect(10, 60, 131, 151))
        self.listaEncendidos.setObjectName("listaEncendidos")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label.setObjectName("label")
        self.listaApagados = QtWidgets.QListWidget(self.groupBox)
        self.listaApagados.setGeometry(QtCore.QRect(180, 60, 131, 151))
        self.listaApagados.setObjectName("listaApagados")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(180, 30, 121, 17))
        self.label_2.setObjectName("label_2")
        self.btnApagar = QtWidgets.QPushButton(self.groupBox)
        self.btnApagar.setGeometry(QtCore.QRect(40, 230, 101, 29))
        self.btnApagar.setObjectName("btnApagar")
        self.btnEncender = QtWidgets.QPushButton(self.groupBox)
        self.btnEncender.setGeometry(QtCore.QRect(206, 230, 101, 29))
        self.btnEncender.setObjectName("btnEncender")
        self.btnReiniciar = QtWidgets.QPushButton(self.groupBox)
        self.btnReiniciar.setGeometry(QtCore.QRect(140, 290, 101, 29))
        self.btnReiniciar.setObjectName("btnReiniciar")
        self.btnApagarTodo = QtWidgets.QPushButton(self.groupBox)
        self.btnApagarTodo.setGeometry(QtCore.QRect(20, 290, 91, 29))
        self.btnApagarTodo.setObjectName("btnApagarTodo")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 10, 401, 541))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 351, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.cpu0bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.cpu0bar.setGeometry(QtCore.QRect(50, 30, 221, 23))
        self.cpu0bar.setProperty("value", 24)
        self.cpu0bar.setInvertedAppearance(False)
        self.cpu0bar.setObjectName("cpu0bar")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 31, 17))
        self.label_4.setObjectName("label_4")
        self.cpu1bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.cpu1bar.setGeometry(QtCore.QRect(50, 70, 221, 23))
        self.cpu1bar.setProperty("value", 24)
        self.cpu1bar.setObjectName("cpu1bar")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 31, 17))
        self.label_5.setObjectName("label_5")
        self.cpu2bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.cpu2bar.setGeometry(QtCore.QRect(50, 110, 221, 23))
        self.cpu2bar.setProperty("value", 24)
        self.cpu2bar.setObjectName("cpu2bar")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 31, 17))
        self.label_6.setObjectName("label_6")
        self.cpu3bar = QtWidgets.QProgressBar(self.groupBox_3)
        self.cpu3bar.setGeometry(QtCore.QRect(50, 150, 221, 23))
        self.cpu3bar.setProperty("value", 24)
        self.cpu3bar.setObjectName("cpu3bar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.label.setText(_translate("MainWindow", "Núcleos Encendidos"))
        self.label_2.setText(_translate("MainWindow", "Núcleos Apagados"))
        self.btnApagar.setText(_translate("MainWindow", "Apagar >"))
        self.btnEncender.setText(_translate("MainWindow", "< Encender"))
        self.btnReiniciar.setText(_translate("MainWindow", "Reiniciar"))
        self.btnApagarTodo.setText(_translate("MainWindow", "Apagar Todo"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Estadísticas"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Actividad en núcleos"))
        self.label_3.setText(_translate("MainWindow", "cpu0"))
        self.label_4.setText(_translate("MainWindow", "cpu1"))
        self.label_5.setText(_translate("MainWindow", "cpu2"))
        self.label_6.setText(_translate("MainWindow", "cpu3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

